#!/bin/bash

REGISTRY="registry.app.enting.org/"
IMAGE="${REGISTRY}ss-landing-page"

docker-build() {
	docker build -t "${IMAGE}" .
}

docker-push() {
	docker push "${IMAGE}"
}

docker-run() {
	docker run -p 3000:3000 "${IMAGE}"
}

app-reload() {
	kubectl rollout restart -n public deploy/ss-landing-page
}

run() {
	npm run dev
}
